spring.application.name=edupulse
server.port=8080

# Active profile (default = dev)
spring.profiles.active=${ENV:dev}

# Multipart (common)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB

# JPA Common
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Connection Pool
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000

# Tomcat logs
server.tomcat.accesslog.enabled=true