# ================= PROD DATABASE (PostgreSQL) =================
spring.datasource.url=jdbc:postgresql://dpg-d0hf7k3e5dus73avlimg-a/lgac2005
spring.datasource.username=root
spring.datasource.password=PWiIDpJqNMwxHCv0kFn9EsY6HfoDGQga

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Disable debug logs
logging.level.org.springframework.security=ERROR
